config/routes.rb
Rails.application.routes.draw do

  # Defines the root path route ("/")
  root "pages#home"

  # home page route handled in pages controller
  get 'pages/home'

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users

  resources :chatrooms do
    # When user views a chatroom, need to be able to search for users to invite
    post :search_for_users
    # chatroom owners can search for users(above), then click on a link to invite user to their chatroom
    put 'invite_to_chatroom/:user_id', to: 'chatrooms#invite_to_chatroom', as: 'invite'
    # When a user has a pending invitation(chatroom.participant entry), they can accept the invitation to join the chatroom
    put 'accept_invitation', to: 'chatrooms#accept_invitation', as: 'accept_invitation'
    # When a user has a pending invitation, they can decline the invitation to join the chatroom
    put 'decline_invitation', to: 'chatrooms#decline_invitation', as: 'decline_invitation'
    # When a user is tired of some dramatic bullshit going on in a chatroom, they can leave that shitty chatroom
    put 'leave_chatroom', to: 'chatrooms#leave_chatroom', as: 'leave'
    # When a chatroom owner is tired of some dramatic bullshit going on in a chatroom, they can kick users from their awesome chatroom
    put 'kick_user/:user_id', to: 'chatrooms#kick_user', as: "kick_user"

    # no index action needed because it's on chatroom/show view,
    # no show action needed because it wouldn't make sense for message to be shown outside chatroom
    resources :messages, except: [:index, :show]

  end


  
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord

    has_many :participants, dependent: :destroy
    has_many :users, through: :participants 

    has_many :messages, dependent: :destroy

    validates :name, presence: true, uniqueness: true

    def owner
        participants_of_type('owned').first
    end
    
    def joined_users
        participants_of_type('joined')
    end

    def all_users_not_pending
        participants_not_of_type('pending')
    end

    scope :ordered, -> { order(id: :asc) }

    # Examples of broadcasting from rails model:
    # full version with all properties set as default values would be like the next 3 lines, see below for short form version of the three lines below  
    #after_create_commit -> { broadcast_prepend_later_to "chatrooms", partial: "chatrooms/chatroom", locals: {chatroom: self}, target: "chatrooms" }
    #after_update_commit -> { broadcast_replace_later_to "chatrooms", partial: "chatrooms/chatroom", locals: {chatroom: self}, target: "chatrooms" }
    #after_destroy_commit -> { broadcast_remove_to "chatrooms" }
    
    # The above three callbacks are equivalent to the following single line, though the above may be beneficial where greater control is needed
    #broadcasts_to ->(chatroom) { [@participation.user, "chatrooms"] }, inserts_by: :prepend


    private
    def participants_of_type(types)
        users.where participants: { participation_type: types } 
    end
    def participants_not_of_type(types)
        users.where.not participants: { participation_type: types } 
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy search_for_users invite_to_chatroom join_chatroom leave_chatroom kick_user ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = current_user.owned_chatrooms.ordered.load_async
    @joined_chatrooms = current_user.joined_chatrooms.ordered.load_async
    @pending_chatrooms = current_user.pending_chatrooms.ordered.load_async
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    @messages = @chatroom.messages.ordered
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = current_user.owned_chatrooms.build(chatroom_params)
    
    respond_to do |format|
      if @chatroom.save
        # once chatroom is validated and saved, create join record to make user the chatroom owner
        Participant.create!(user: current_user, chatroom: @chatroom, participation_type: "owned")

        # broadcasting from controller(instead of chatroom model) so devise current_user can be used in view... NOW ACTUALLY Using model, and switched to using multiple view files, instead of a view file with current_user based conditionals
        #@chatroom.broadcast_prepend_later_to "chatrooms", target: "owned_chatrooms", locals: {chatroom: @chatroom, current_user: current_user}
        #@chatroom.broadcast_update_to Chatroom.new, ""
        
        format.turbo_stream { flash.now[:notice] = "Chatroom was successfully created." }
        format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully created." }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        # broadcasting from controller so we can send devises current_user to the view loaded via turbo stream broadcast(?)
        @chatroom.broadcast_replace_later_to @chatroom, locals: {chatroom: @chatroom, current_user: current_user}
        format.turbo_stream { flash.now[:notice] = "Chatroom was successfully updated." }
        format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Chatroom was successfully deleted." }
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  ####################################################################
    # Custom actions that aren't part of scaffolding added below #
  ####################################################################

  # POST chatrooms/search_for_users_chatrooms_path
  def search_for_users

    if params.dig(:email_search).present?
      @users = User.search_by_email(params[:email_search], @chatroom)
    else
      @users = []
    end

    respond_to do |format|
      format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("search_for_users_results",
            partial: "chatrooms/search_for_users_results",
            locals: { users: @users, chatroom: @chatroom })
          ]
      end
    end
  end

  # PUT chatrooms/:chatroom_id/invite_to_chatroom/:user_id
  def invite_to_chatroom
    @user = User.find(params[:user_id])

    # create participation in the @chatroom for @user and set the participation_type to be "pending"
    @participation = @chatroom.participants.build(user: @user, chatroom: @chatroom, participation_type: "pending")

    respond_to do |format|
      if @participation.save
        # Now that user is invited(@participation.save), broadcast the respective chatroom with the chatroom_pending partial to the invited users list of pending chatrooms
        @chatroom.broadcast_prepend_later_to [@participation.user, "chatrooms"], target: "pending_chatrooms", partial: "chatrooms/chatroom_pending", locals: {chatroom_pending: @chatroom}
        
        format.turbo_stream { flash.now[:notice] = "User has been invited to your chatroom." }
        format.html { redirect_to chatroom_path(@chatroom), notice: "User has been invited to your chatroom." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT chatrooms/:chatroom_id/accept_invitation
  def accept_invitation
    @chatroom = Chatroom.find(params[:chatroom_id])
     
    # find participation with current_user, the chatroom the request was made from, and where the participation_type is set to pending
    @participation = @chatroom.participants.find_by(user: current_user, chatroom: @chatroom, participation_type: "pending")

    respond_to do |format|
      if @participation.update(participation_type: 'joined')

        # Now that invited user has joined chatroom, broadcast the new user to the list of chatroom users.
        @chatroom.broadcast_append_later_to [@chatroom, "users"], target: "chatroom_users", partial: "chatrooms/user", locals: {user: @participation.user}
        
        format.turbo_stream { flash.now[:notice] = "You have successfully joined the chatroom." }
        format.html { redirect_to chatrooms_path, notice: "You have successfully joined the chatroom." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  # PUT chatrooms/:chatroom_id/decline_invitation
  def decline_invitation
    @chatroom = Chatroom.find(params[:chatroom_id])
     
    # find participation with current_user, the chatroom the request was made from, and where the participation_type is set to pending
    @participation = @chatroom.participants.find_by(user: current_user, chatroom: @chatroom, participation_type: "pending")

    respond_to do |format|
      if @participation.delete

        # Invited user has declined the chatroom invitation, so remove the chatroom from their pending chatrooms list
        @chatroom.broadcast_remove_to [@participation.user, "chatrooms"], target: "chatroom_#{@chatroom.id}"
        
        format.turbo_stream { flash.now[:notice] = "You have successfully joined the chatroom." }
        format.html { redirect_to chatrooms_path, notice: "You have successfully joined the chatroom." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  # PUT chatrooms/:chatroom_id/leave_chatroom
  def leave_chatroom
     
    # find participation with current_user, the chatroom the request was made from, and where the participation_type is set to joined
    @participation = @chatroom.participants.find_by(user: current_user, chatroom: @chatroom, participation_type: "joined")

    respond_to do |format|
      if @participation.delete

        @chatroom.broadcast_remove_to [@chatroom, "users"], target: "user_#{current_user.id}"

        format.turbo_stream { flash.now[:notice] = "You have successfully left " + @chatroom.name }
        format.html { redirect_to chatrooms_path, notice: "You have successfully joined the chatroom." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  # PUT chatrooms/:chatroom_id/chatroom_kick_user/:user_id
  def kick_user
     
    # find participation with kicked user, the chatroom the request was made from, and where the participation_type is set to joined
    @participation = @chatroom.participants.find_by(user_id: params[:user_id], chatroom: @chatroom, participation_type: "joined")

    respond_to do |format|
      if @participation.delete

        @chatroom.broadcast_remove_to [@chatroom, "users"], target: "user_#{params[:user_id]}"

        @chatroom.broadcast_remove_to [@participation.user, "chatrooms"]
        
        format.turbo_stream { flash.now[:notice] = "You have successfully kicked user #{params[:user_id]}" }
        format.html { redirect_to chatrooms_path, notice: "You have successfully joined the chatroom." }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      if params[:chatroom_id]
        @chatroom = Chatroom.find(params[:chatroom_id])      
      else
        @chatroom = Chatroom.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name, :description, :chatroom_id)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chatroom.html.erb
<%= turbo_frame_tag chatroom do %>
  <article class="chatroom_card">
    
    <div class="chatroom_card_content">
      <h3 class="chatroom_card_title">
        <%= link_to chatroom.name, 
              chatroom_url(chatroom),
              data: { turbo_frame: "_top" }, 
              #class: "", 
              title: "Enter this Chatroom" %>
      </h3>
      <p class="chatroom_card_description"><%= chatroom.description %></p>
      <p>Owner <%= chatroom.owner.username %></p>
      <p>
        <%= chatroom.users.size %>
        <span class="material-icons">group</span>
      </p>
    </div>

    <div class="actions">
        <%= link_to "fullscreen", 
              chatroom_path(chatroom), 
              data: { turbo_frame: "_top" }, 
              class: "btn material-icons-outlined", 
              title: "Enter this Chatroom" %>
        <%= link_to "edit", 
            edit_chatroom_path(chatroom), 
            data: { turbo_frame: "chatroom_#{chatroom.id}" }, 
            class: "btn material-icons-outlined", 
            title: "Edit chatroom details" %>

        <%= button_to "delete_forever", 
              chatroom_path(chatroom), 
              method: :delete, 
              class: "material-icons-outlined", 
              form: { data: { turbo_confirm: 'This will delete the Chatroom and all its Messages forever. Are you sure?' } } %>
    </div>

  </article>
<% end %>

app/views/chatrooms/_search_for_users_form.html.erb
<%= form_with url: chatroom_search_for_users_path(@chatroom), 
    method: :post,
    data: {
        controller: 'debounce',
        debounce_target: 'form'
    } do |form| %>

    <%= form.search_field :email_search, value: params[:email_search], data: { action: "input->debounce#search" }, autocomplete: "off", placeholder: "Search for users" %>
<% end %>

 <div id="search_for_users_results"></div>

app/views/chatrooms/_search_for_users_results.html.erb
<% users.each do |user| %>
  <br>
  <%= button_to chatroom_invite_path(@chatroom, user), method: :put, form: { id: "potential_user_#{user.id}"} do %>
    <%= highlight(user.email, params.dig(:email_search)) %>
  <% end %>
<% end %>

app/views/chatrooms/_user.html.erb
<div id="<%= dom_id(user) %>">
    <%= user.username %>
    <% if user != chatroom.owner %>
        <%= button_to "person_remove", 
              chatroom_kick_user_path(chatroom, user), 
              method: :put, 
              class: "material-icons-outlined" %>
    <% end %>
</div>

app/views/chatrooms/accept_invitation.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<!-- Remove chatroom from list of chatrooms with pending invitation -->
<%= turbo_stream.remove "chatroom_#{@participation.chatroom.id}" %>
<!-- Add chatroom to list of joined chatrooms -->
<%= turbo_stream.prepend "joined_chatrooms" do %>
    <%= render "chatroom_joined", chatroom_joined: @participation.chatroom %>
<% end %>

app/views/chatrooms/create.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.prepend "owned_chatrooms", @chatroom %>
<%= turbo_stream.replace Chatroom.new, "" %>

app/views/chatrooms/destroy.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.remove @chatroom %>

app/views/chatrooms/edit.html.erb
<h1>Editing chatroom</h1>

<%= turbo_frame_tag @chatroom do %>
  <%= render "form", chatroom: @chatroom %>
<% end %>

<br>

<div>
  <%= link_to "Show this chatroom", @chatroom %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/invite_to_chatroom.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.remove "potential_user_#{@participation.user.id}"%>

app/views/chatrooms/join_chatroom.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<!-- Remove chatroom from list of chatrooms with pending invitation -->
<%= turbo_stream.remove "chatroom_#{@participation.chatroom.id}" %>
<!-- Add chatroom to list of joined chatrooms -->
<%= turbo_stream.prepend "joined_chatrooms" do %>
    <%= render "chatroom_joined", chatroom_joined: @participation.chatroom %>
<% end %>

app/views/chatrooms/kick_user.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

app/views/chatrooms/leave_chatroom.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.remove "chatroom_#{@participation.chatroom.id}" %>

app/views/chatrooms/new.html.erb
<h1>New chatroom</h1>

<%= turbo_frame_tag @chatroom do %>
  <%= render "form", chatroom: @chatroom %>
<% end %>

<br>

<div>
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/update.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>
<%= turbo_stream.replace @chatroom %>